import type { Config } from "tailwindcss";

const config: Config = {
  content: ["./app/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}", "./lib/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        white: "#f8f4e8",
        cream: "#f8f4e8",
        "outline-variant": "#315a48",
        "on-error-container": "#ffdad6",
        "surface-tint": "#49e68e",
        "on-secondary-fixed": "#052d1d",
        "on-surface-variant": "#bccbbd",
        "surface-bright": "#174b38",
        primary: "#49e68e",
        "on-primary": "#052d1d",
        outline: "#779988",
        "surface-container-lowest": "#041912",
        "on-background": "#f8f4e8",
        "error-container": "#93000a",
        "surface-dim": "#061d15",
        "inverse-primary": "#087847",
        "on-secondary-container": "#c7d8c3",
        "tertiary-fixed": "#e8f0df",
        "on-tertiary-fixed-variant": "#324c44",
        background: "#071f17",
        "surface-container": "#0d3326",
        "on-secondary": "#12362d",
        "on-tertiary": "#1b352e",
        "on-primary-fixed-variant": "#075c39",
        "primary-fixed": "#6ff0a8",
        "secondary-container": "#2c5946",
        "on-surface": "#f8f4e8",
        "inverse-surface": "#f8f4e8",
        "on-error": "#690005",
        "on-primary-container": "#063d27",
        "on-primary-fixed": "#052d1d",
        "primary-fixed-dim": "#49e68e",
        "on-secondary-fixed-variant": "#2a4d43",
        "on-tertiary-fixed": "#05201a",
        "surface-container-high": "#12402f",
        "secondary-fixed": "#e3ead8",
        "surface-variant": "#174735",
        "tertiary-fixed-dim": "#d8dfcd",
        secondary: "#c7d8c3",
        "tertiary-container": "#9db5a3",
        "primary-container": "#159c5e",
        tertiary: "#d8dfcd",
        "surface-container-highest": "#174735",
        "secondary-fixed-dim": "#c7d8c3",
        "on-tertiary-container": "#243e37",
        error: "#ffb4ab",
        "surface-container-low": "#0a2a20",
        surface: "#071f17",
        "inverse-on-surface": "#25332e",
        ink: "#071f17",
        mantle: "#0a2a20",
        panel: "#0d3326",
        panel2: "#12402f",
        line: "#315a48",
        text: "#f8f4e8",
        muted: "#b4c6b7",
        mint: "#49e68e",
        mint2: "#6ff0a8",
        sage: "#d8dfcd"
      },
      fontFamily: {
        sans: ["DM Sans", "ui-sans-serif", "system-ui", "sans-serif"],
        display: ["Sora", "DM Sans", "ui-sans-serif", "system-ui", "sans-serif"],
        mono: ["ui-monospace", "SFMono-Regular", "Menlo", "monospace"],
        "label-md": ["DM Sans", "ui-sans-serif", "system-ui", "sans-serif"],
        "mono-data": ["JetBrains Mono", "ui-monospace", "SFMono-Regular", "Menlo", "monospace"],
        "display-lg": ["Sora", "DM Sans", "ui-sans-serif", "system-ui", "sans-serif"],
        "body-md": ["DM Sans", "ui-sans-serif", "system-ui", "sans-serif"],
        "headline-md": ["Sora", "DM Sans", "ui-sans-serif", "system-ui", "sans-serif"],
        "headline-lg-mobile": ["Sora", "DM Sans", "ui-sans-serif", "system-ui", "sans-serif"],
        "body-lg": ["DM Sans", "ui-sans-serif", "system-ui", "sans-serif"],
        "headline-lg": ["Sora", "DM Sans", "ui-sans-serif", "system-ui", "sans-serif"]
      },
      fontSize: {
        xs: ["11px", { lineHeight: "1.45" }],
        sm: ["13px", { lineHeight: "1.5" }],
        base: ["14px", { lineHeight: "1.55" }],
        lg: ["16px", { lineHeight: "1.45" }],
        xl: ["19px", { lineHeight: "1.35" }],
        "2xl": ["22px", { lineHeight: "1.3" }],
        "3xl": ["28px", { lineHeight: "1.18" }],
        "label-md": ["11px", { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "600" }],
        "mono-data": ["12px", { lineHeight: "1", letterSpacing: "-0.01em", fontWeight: "500" }],
        "display-lg": ["42px", { lineHeight: "1.08", letterSpacing: "-0.025em", fontWeight: "600" }],
        "body-md": ["13px", { lineHeight: "1.5", fontWeight: "400" }],
        "headline-md": ["21px", { lineHeight: "1.3", fontWeight: "600" }],
        "headline-lg-mobile": ["25px", { lineHeight: "1.2", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "1.55", fontWeight: "400" }],
        "headline-lg": ["28px", { lineHeight: "1.2", fontWeight: "600" }]
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem"
      },
      spacing: {
        unit: "4px",
        gutter: "16px",
        "margin-mobile": "16px",
        "margin-desktop": "32px",
        "container-max": "1440px"
      },
      boxShadow: {
        glow: "0 0 32px rgba(73, 230, 142, 0.13)",
        panel: "0 24px 70px rgba(0, 0, 0, 0.28)"
      }
    }
  },
  plugins: []
};

export default config;
